import os
BOT_TOKEN=os.environ['BOT_TOKEN']
USE_INVITE_SERVER=os.environ['USE_INVITE']=='true'
PUNISH_ROLES=(1279588925257683014,)
REDIS_URL=os.environ['REDIS_URL']
REDIS_USER=os.environ['REDIS_USER']
REDIS_PSW=os.environ['REDIS_PSW']